* Library Information
* Sweetgreen.el

[[https://github.com/syl20bnr/spacemacs][file:https://cdn.rawgit.com/syl20bnr/spacemacs/442d025779da2f62fc86c2082703697714db6514/assets/spacemacs-badge.svg]]

Have you ever wanted to just order your salad without leaving your favorite
editor? Now you can!


[[Sweetgreen][file:sweetgreen.png]]
* Functions & macros
** Interactive Functions

** Internal Functions

*** =>
=> is an alias for ==>=,
which is not defined.  Please make a bug report.

*** cancel-item
cancel-item is an alias for =cancel-item=,
which is not defined.  Please make a bug report.

*** cancel-orders
cancel-orders is an alias for =cancel-orders=,
which is not defined.  Please make a bug report.

*** checkout
checkout is an alias for =checkout=,
which is not defined.  Please make a bug report.

*** sweetgreen
sweetgreen is an alias for =sweetgreen=,
which is not defined.  Please make a bug report.

*** sweetgreen//add-to-cart
sweetgreen//add-to-cart is an alias for =sweetgreen//add-to-cart=,
which is not defined.  Please make a bug report.

*** sweetgreen//auth
sweetgreen//auth is an alias for =sweetgreen//auth=,
which is not defined.  Please make a bug report.

*** sweetgreen//fetch-auth-cookie
sweetgreen//fetch-auth-cookie is an alias for =sweetgreen//fetch-auth-cookie=,
which is not defined.  Please make a bug report.

*** sweetgreen//fetch-basket
sweetgreen//fetch-basket is an alias for =sweetgreen//fetch-basket=,
which is not defined.  Please make a bug report.

*** sweetgreen//fetch-csrf-token
sweetgreen//fetch-csrf-token is an alias for =sweetgreen//fetch-csrf-token=,
which is not defined.  Please make a bug report.

*** sweetgreen//get-menu
sweetgreen//get-menu is an alias for =sweetgreen//get-menu=,
which is not defined.  Please make a bug report.

*** sweetgreen//get-restaurants
sweetgreen//get-restaurants is an alias for =sweetgreen//get-restaurants=,
which is not defined.  Please make a bug report.

*** sweetgreen//logout
sweetgreen//logout is an alias for =sweetgreen//logout=,
which is not defined.  Please make a bug report.

*** sweetgreen//make-helm-menu-sources
sweetgreen//make-helm-menu-sources is an alias for =sweetgreen//make-helm-menu-sources=,
which is not defined.  Please make a bug report.

*** sweetgreen//order-product
sweetgreen//order-product is an alias for =sweetgreen//order-product=,
which is not defined.  Please make a bug report.

*** sweetgreen//select-time
sweetgreen//select-time is an alias for =sweetgreen//select-time=,
which is not defined.  Please make a bug report.

*** sweetgreen/confirm-product
sweetgreen/confirm-product is an alias for =sweetgreen/confirm-product=,
which is not defined.  Please make a bug report.

*** sweetgreen/helm-menu
sweetgreen/helm-menu is an alias for =sweetgreen/helm-menu=,
which is not defined.  Please make a bug report.

*** sweetgreen/helm-restaurants
sweetgreen/helm-restaurants is an alias for =sweetgreen/helm-restaurants=,
which is not defined.  Please make a bug report.

*** sweetgreen/helm-wanted-time
sweetgreen/helm-wanted-time is an alias for =sweetgreen/helm-wanted-time=,
which is not defined.  Please make a bug report.

** Macros
* Variables
** Customizable Variables

*** sweetgreen--password
Sweetgreen Account Password

*** sweetgreen--username
Sweetgreen Accounr Username

** Internal Variables

*** sweetgreen--cookie-regexp
Regular expression to get the Session ID from the response's headers.

*** sweetgreen--cookie-string
Cookies for http://orders.sweetgreen.com

*** sweetgreen--csrf-token
CSRF Token for http://orders.sweetgreen.com

*** sweetgreen--csrf-token-regexp
Regular Expression used to grab the CSRF Token from the index page.

*** sweetgreen--curr-restaurant
Current Restaurant

*** sweetgreen--menu-alist
Menu for Current restaurant

*** sweetgreen--products-alist
Menu for Current restaurant

*** sweetgreen--restaurants-alist
Nearby Restaurants alist
